lib/inn_checker_web/router.ex
defmodule InnCheckerWeb.Router do
  use InnCheckerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", InnCheckerWeb do
    pipe_through :browser
    
    get "/", HistoryController, :index
    post "/", HistoryController, :check
  end
end

lib/inn_checker/application.ex
defmodule InnChecker.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      InnChecker.Repo,
      # Start the endpoint when the application starts
      InnCheckerWeb.Endpoint
      # Starts a worker by calling: InnChecker.Worker.start_link(arg)
      # {InnChecker.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: InnChecker.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    InnCheckerWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/inn_checker/checks/checks.ex
defmodule InnChecker.Checks do
  @moduledoc """
  The Checks context.
  """
  use Timex
  import Ecto.Query, warn: false
  alias InnChecker.Repo
  alias InnChecker.Checks.History

  @doc """
  Returns the list of checks_history.
  """
  def list_checks_history do
    Repo.all(from h in History, order_by: [desc: :inserted_at])
    |> Enum.map(fn check -> 
      %{check | inserted_at: format_date(check.inserted_at)} end)
  end

  def format_date(date) do
    {:ok, date} = 
      Timezone.convert(date, "Europe/Moscow")
      |> Timex.format("[{D}.{0M}.{YYYY} {h24}:{m}]")
    date
  end

  @doc """
  Creates a new inn check.
  """
  def create_check(inn) do
    case validate_inn(inn) do
      {:ok, inn, length} ->
        inn_list = String.to_integer(inn)
        |> Integer.digits()
        
        valid = if length == 10 do
          is_valid_inn_sequence?(Enum.slice(inn_list, 0..8), List.last(inn_list))
        else
          [check_sum1, check_sum2] = Enum.slice(inn_list, -2..-1)     
          is_valid_inn_sequence?(Enum.slice(inn_list, 0..9), check_sum1) && 
          is_valid_inn_sequence?(Enum.slice(inn_list, 0..10), check_sum2)
        end
          
        History.changeset(%History{}, %{"inn" => inn, "valid" => valid}) |> Repo.insert

      {:error, reason} -> {:error, reason}
    end
  end
  
  @doc """
  Provides input validation

  ## Examples

    iex> InnChecker.Checks.validate_inn("")
    {:error, "Нужно заполнить"}
    iex> InnChecker.Checks.validate_inn("908234")
    {:error, "Должен быть длинной в 10 или 12 цифр"}

  """
  def validate_inn(inn) do
    inn = String.trim(inn)
    length = String.length(inn)
    cond do
      inn == "" ->
        {:error, "Нужно заполнить"}

      !Regex.match?(~r{^\d+$}, inn) ->
        {:error, "Должен состоять только из цифр"}
    
      length != 10 && length != 12 ->
        {:error, "Должен быть длинной в 10 или 12 цифр"}
      
      Repo.one(from h in History, where: h.inn == ^inn) ->
        {:error, "Уже проверяли"}

      true -> {:ok, inn, length}
    end
  end

  @doc """
  Determines wheter inn sequence is correct

  ## Examples

    iex> InnChecker.Checks.is_valid_inn_sequence?([6,3,1,6,1,4,5,6,7], 7)
    true

    # iex> InnChecker.Checks.is_valid_inn_sequence?([5,0,2,1,0], 5)
    false

  """
  def is_valid_inn_sequence?(seq, check_sum) do
    base = [2, 4, 10, 3, 5, 9, 4, 6, 8]
    mults = case length(seq) do
      9 -> base
      10 -> [7] ++ base
      11 -> [3, 7] ++ base
    end

    rem = Enum.zip(seq, mults)
    |> Enum.map(fn {item, mult} -> item * mult end)
    |> Enum.sum()
    |> rem(11)
    |> rem(10)

    rem == check_sum
  end
end

lib/inn_checker/checks/history.ex
defmodule InnChecker.Checks.History do
  use Ecto.Schema
  import Ecto.Changeset

  @derive {Jason.Encoder, only: [:inn, :valid, :inserted_at]}

  schema "checks_history" do
    field :inn, :string
    field :valid, :boolean, default: false

    timestamps()
  end

  @doc false
  def changeset(history, attrs) do
    history
    |> cast(attrs, [:inn, :valid])
    |> validate_required([:inn], message: "Нужно заполнить")
    |> validate_format(:inn, ~r{^\d+$}, message: "Должен состоять только из цифр")
    |> validate_format(:inn, ~r/^(\d{10}|\d{12})$/, message: "Должен быть длинной в 10 или 12 цифр")
  end
end

lib/inn_checker/repo.ex
defmodule InnChecker.Repo do
  use Ecto.Repo,
    otp_app: :inn_checker,
    adapter: Ecto.Adapters.Postgres
end

lib/inn_checker_web/controllers/history_controller.ex
defmodule InnCheckerWeb.HistoryController do
  use InnCheckerWeb, :controller
  alias InnChecker.Checks

  def index(conn, _params) do
    render(conn, "index.html", checks_history: Checks.list_checks_history(), input: "", error: "")
  end

  def check(conn, %{"inn" => inn}) do
    case Checks.create_check(inn) do
      {:ok, _new_check} ->
        render(conn, "index.html", checks_history: Checks.list_checks_history(), input: "", error: "")
      {:error, error} ->
        render(conn, "index.html", checks_history: Checks.list_checks_history(), input: inn, error: error)
    end
  end
end

lib/inn_checker_web/views/error_view.ex
defmodule InnCheckerWeb.ErrorView do
  use InnCheckerWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/inn_checker_web/views/history_view.ex
defmodule InnCheckerWeb.HistoryView do
  use InnCheckerWeb, :view
end

lib/inn_checker_web/views/layout_view.ex
defmodule InnCheckerWeb.LayoutView do
  use InnCheckerWeb, :view
end

lib/inn_checker_web/templates/history/index.html.eex
<section class="inn-check">
  <h1 class="inn-check__header">Проверка ИНН <br> для юридических и физических лиц</h1>
  <%= form_tag Routes.history_path(@conn, :index), method: "post", class: "inn-check__form" do %>
    <div class="input-group">
      <label for="inn-validate">Введите ИНН</label>
      <input type="text" id="inn-validate" class="inn-check__validate-input" name="inn" value="<%= @input %>">
      <span class="inn-check__error"><%= @error %></span>
    </div>
    <input type="submit" value="Отправить">
  <% end %>

  <%= if @checks_history do %>
    <ul class="inn-check__list">
      <%= for check <- @checks_history do %>
        <li class="inn-check__list-item">
          <span class="inn-check__date"><%= check.inserted_at %></span>
          <div class="inn-group">
            <span class="inn-check__number">&nbsp;<%= check.inn %> : </span>
            <%= if check.valid do %>
              <span class="inn-valid">корректен</span>
          <% else %>
              <span class="inn-invalid">некорректен</span>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>  
  <% end %>
</section>

lib/inn_checker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Проверка ИНН</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
  </head>
  <body>
    <main role="main" class="container">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>